### PR TITLE
Update start.sh

### PR DESCRIPTION
**Pull request by yurturdev**
@race-of-sloths

### CODE REVIEW

**Comment by race-of-sloths** [comment]
Hello, Maintainer! 👋 @yurturdev has submitted another valuable pull request in the Race of Sloths. We appreciate their continued efforts to enhance the project. Your review will help further their contribution's impact.

<details>
<summary>Learn more about the race and how your feedback drives our community forward.</summary>

Use `@race-of-sloths reject` to exclude this PR from the race, `@race-of-sloths score [1/2/3/5/8/13]` to award points, or `@race-of-sloths pause` to stop my notifications for your repository. For more on how the race runs and our scoring nuances, check out this [link](https://github.com/race-of-sloths).
</details>

**Comment by akorchyn** [comment]
@race-of-sloths score 13

**Comment by race-of-sloths** [comment]
🏆 Great work! Your score has been recorded for the Race of Sloths! 🦥✨

Attention, fellow reviewers: Remember, you have 24 hours to submit additional scores after the pull request is merged. Stay tuned to this thread for the final score announcement!

**Comment by race-of-sloths** [comment]
🚀 Woohoo! The PR has been merged with the current score of 13. The scoring process will close automatically in 24 hours! ⏳🕒

**Comment by race-of-sloths** [comment]
✅ Great job! The PR is finalized. Your contribution is much appreciated. Scoring is now wrapped up! 🎊

**Pull request merged**
